Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2023
Var
nu,metade,nusem:real;
inicio
escreval("Digite um número:")
 leia(nu)
metade<-(nu)/2
se(nu>20)entao
escreval("A metade é:",metade)
senao
escreval(nu)
fimse


Fimalgoritmo