Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2023
Var
nu1,nu2,dife:inteiro;
inicio
escreval("Digite o primeiro número:")
 leia(nu1)
escreval("Digite o segundo número:")
 leia(nu2)

se(nu1>nu2)entao
dife<-(nu1-nu2)
escreval(dife)
senao
dife<-(nu2-nu1)
escreval(dife)
fimse



Fimalgoritmo