Algoritmo "semnome"
// Disciplina   : [Mundo do trabalho]
// Professor   : Natália
// Data:24/04/2023
// Autor(a)    : Bruna

Var
  nota1,nota2,nota3,nota4,soma:inteiro;
inicio
Escreval("escreva o primeiro número:")
 leia(nota1)
escreval("escreca o segundo número:")
 leia(nota2)
escreval("escreva o terceiro número:")
 leia(nota3)
escreval("escreva o quarto número:")
 leia(nota4)
soma <-(nota1+nota2+nota3+nota4)
Fimalgoritmo //end