Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2023
Var
nu1,nu2,nu3,media:real;
inicio
escreval("Digito o primeiro número:")
 leia(nu1)
escreval("Digite o segundo número:")
 leia(nu2)
escreval("Digite o terceiro número:")
 leia(nu3)
media<-(nu1+nu2+nu3)/3
escreval("a media é:",media)
fimalgoritmo
 